defaults:
  - logging: info
  - model@models.0: timesfm
  - model@models.1: chronos
  - model@models.2: flowstate
  - ensemble: slsqp
  - imputation: dummy_value
  - data: dataset # List of dataset name-term pairs 
  - _self_

# Redirect hydra output
hydra:
  run:
    dir: ./output/hydra

# Seed for reproducibility
seed: 42
workers: true
verbose: true

# Batch size to use for model forward passes
model_batch_size: 64

# Metric to optimize when computing ensemble weights during cross-validation
metric: mae

# Batch size to use when processing datasets
data_batch_size: 1024

# Number of cross-validation windows to use when computing ensemble weights
n_windows: 1
